
.. _On-Premise: http://on-premise.enstratus.com
.. _オンプレミス: http://enstratus.creationline.com/on-premise/
.. _SaaS (en): http://docs.enstratus.com
.. _SaaS: http://enstratus.creationline.com/saas/
.. _Advanced Automation: http://automation.enstratus.com
.. _高度な自動化機能: http://enstratus.creationline.com/automation/
.. _enStratus Agent: http://agent.enstratus.com
.. _enStratus エージェント: http://enstratus.creationline.com/agent/
.. _チュートリアル: http://enstratus.creationline.com/tutorials/

.. _Notifications: http://docs.enstratus.com/console/notifications.html
.. _通知機能: http://enstratus.creationline.com/saas/console/notifications.html
.. _Identify and Access Management: http://docs.enstratus.com/users/iam.html
.. _識別とアクセス管理: http://enstratus.creationline.com/saas/users/iam.html
